apiVersion: v1
data:
    APP_API_KEY: ENC[AES256_GCM,data:dwKefxk4ispcO2TubU0BaswGMqfufUSEkd/bkR+ZDXqNX/ukExYr3w+KaVqcAOVqmbUCDNtyw3uP+MZtCiKIkQ==,iv:uFzbbcskj01yEQDEvi43oyD8fJk57RvhWd3oErP2+64=,tag:0o+kYe0bOiRCnnaAzaR1LA==,type:str]
    MANIFEST_API_KEY: ENC[AES256_GCM,data:eGm7rUoVnByiyTQiWvtaWs6sRJK7dPJIv/W4zAA/uAm/8lGnlaBJcvN7AJ/R5wmELeUn+0ZpyPZA0gz4afB/gJxI6S4=,iv:i5C69/v2yKrG5UFpkp7KND3X9ZvXRHuUuNddFE3XLPY=,tag:/10Ccq1sTYqa20YySaQ6dQ==,type:str]
    ZAI_CODING_API_KEY: ENC[AES256_GCM,data:9q2DptV0kSQ/AbWDQHm29asYtz7Aw4SFvEgUW5awdPjpVoqVchaCttnxnTwDzM+xhjFrzbewJlxFwfv7079Q7Drqa6c=,iv:ZP9ndf9/YOYMUq7LdL09FggLKir4Fbbdgbx1kQ63I7c=,tag:mI3BhIbG5t3d58/TM3MxEA==,type:str]
kind: Secret
metadata:
    name: app-secrets
    namespace: llm-gateway
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT044YVZWUkRvZW9FbU13
            dW5pZklvZzBYb293UDA1OGpYRlVkY1h3TmdFCjFNUlloQkgyOEtNcE9SNTZoNnFm
            MGZpZnV2dVp0MElIT3lINXUwZzZ5Qm8KLS0tIDgxbzYvdEIyaDlDRXEwek5wYW5i
            ekhUaHZQNDdDMGhpV2tYK1ZNMnVUdTQKpAdnfN/UAUq/rqu/8vfoOFPVatWMD/1b
            GHX/ENrRSR1ziKFQfJZhrhI5Pwnuyl+wTCkk1+w4Vd1is5cEnoA2Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ww7lffn57hz5h2x7qrjaud70fvnzjp4wnrtze2tde9uj4u0e34yq7y748d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T09:28:26Z"
    mac: ENC[AES256_GCM,data:d7MEOPiKvDvsD4dq/aKzkXOiehW2Z8fpuLbpJRmznuCiA8cftIdOWMjVBy4lGoNJLWqNbJfwyH+zYbV+k5cURY0unfvg/e2bdN9jNp+FoWek1aahhLcj1vG/WB29kLV/btSVldOzj6wkK3F9H5KXfknZNX4VcbYVjB3ZjgvOb1I=,iv:QQyd8IPeAbZVV9xeb6zkdlS3bbXeT8Td/QDL8AF+N1A=,tag:9g3Qd+c2jBM4bX6pCYzh+Q==,type:str]
    version: 3.13.3
