apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:euxvypG3prv4EpLcOelw3KQS2FPhB4AebYKsmj3JUf5dwIi/IaHNmJXcoOrFh//HeN8bdWE2rxIcJQRuIvcsqqrO43DQ3DGP+o2VX2l9qcthH+RlOYlLJFO5HCnogcpecWyMTf157FlhbXey023oJTeGZ4/BCVhd0g/UhqkFgJv9Gk8VFc/5SaE8dBZ467nd933CJzOfxH8BsDmZK0nolR5kf9beXOXyuwolUPR4KBjaWVhe+veU1/q3JM5i+IyB0wQKvKBNk/xfDxfdjO/YtrDFf1JwcOHABqqleWIk5fG6Kwag1MuWdPLAxL0nRx/M,iv:V+GRsnxGTJiDETGEc/DyeQGiLEzLdYmJKBOhdehg1Pk=,tag:59AhMpMaOQcdh+2VhTkXXw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: llm-gateway
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NWZkVlYxd0VYUG5nVUZa
            SzdtTVVTak90NkcvSFJwb0dDSjhqc1VuRFY0Ci9QdUVlVXJVdkcrbGszanpQZlQ4
            T0tCbGtCRENaT3drOE1JMytNbkF0dUUKLS0tIFpaV3Q2a0VTWllKNG9STG5XcElV
            T1ZhSkphMzdHWjhNcldBZEVicGxuUXMKjoWIALdKC5Kuqdx1xpumUq4jNCQ4QGvi
            0sKW6WIAXutjlQ/t/iTj1Na2n1wwyuDpQwsK6wJj9ZphKDtLFXli0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ww7lffn57hz5h2x7qrjaud70fvnzjp4wnrtze2tde9uj4u0e34yq7y748d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T09:28:26Z"
    mac: ENC[AES256_GCM,data:kyG0xEk+0lTeP8QwA94Ca/Kw9joiAHS+7LRBhMNSR+AgTZkVnXjMf5Oz3otV2UbBzxzSMbLeiUxGskc64c1ETTOOhEyzs4fDbTUM8IqK2N9j20iE/emB9EthtnO6XjqaXjPhLkpsElt19DtYfWCkRWqxcXZ4QajO0+fQ5m2EDVc=,iv:FSvRpFTPfoB0IakWcLosSGsACrlsdcjSXhVy3/hb8iM=,tag:e2PdsKodLyfU5j2jiYz1tA==,type:str]
    version: 3.13.3
